export const colors = {
  darkGray: "#1f1300",
  gray: "#2A3338",
  offWhite: "#f2f7f2",
  darkRed: "#7d2d26",
  red: "#CE675E",
  lightRed: "#dc928b",
  darkOrange: "#c26100",
  orange: "#FF8811",
  lightOrange: "#ffa54c",
  darkYellow: "#edb214",
  yellow: "#F4D06F",
  lightYellow: "#f8e2a6",
  darkBlue: "#1446a0",
  blue: "#1b5dd4",
  lightBlue: "#6595ec",
  darkGreen: "#0A5A3F",
  green: "#108f64",
  lightGreen: "#16c489",
};

export const colorPickerOptions = [
  "#000000",
  colors.darkGray,
  colors.gray,
  colors.offWhite,
  "#FFFFFF",
  colors.darkRed,
  colors.red,
  colors.lightRed,
  colors.darkOrange,
  colors.orange,
  colors.lightOrange,
  colors.darkYellow,
  colors.yellow,
  colors.lightYellow,
  colors.darkGreen,
  colors.green,
  colors.lightGreen,
  colors.darkBlue,
  colors.blue,
  colors.lightBlue,
];
